# Generated by Django 2.1.2 on 2018-11-20 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='name',
            new_name='label',
        ),
    ]
